# Generated by Django 3.1.7 on 2021-07-23 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0025_auto_20210701_1736'),
        ('payment', '0003_auto_20210702_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=150)),
                ('third_party_subscription', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='', max_length=100)),
                ('source', models.CharField(default='', max_length=100)),
                ('transaction_id', models.CharField(default='', max_length=255)),
                ('created_at', models.DateField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaypalCustomer',
        ),
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
    ]
