# Generated by Django 3.1.7 on 2021-02-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210217_0724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
