# Generated by Django 3.1.6 on 2021-02-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190302_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ca_no',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Company Admin'), ('2', 'Branch Admin'), ('2', 'Filed Executive')], max_length=30, null=True),
        ),
    ]
