# Generated by Django 3.1.6 on 2021-02-17 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190302_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ca_no',
        ),
    ]
