# Generated by Django 3.1.6 on 2021-02-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210217_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Company Admin'), ('2', 'Branch Admin'), ('3', 'Filed Executive')], max_length=30, null=True),
        ),
    ]
