# Generated by Django 3.1.7 on 2021-04-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_enabled_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_profile',
            field=models.BooleanField(default=False),
        ),
    ]
