# Generated by Django 3.1.7 on 2021-07-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='social_profile_pic',
            field=models.CharField(blank=True, help_text='Link your Social profile pic', max_length=255, null=True),
        ),
    ]
