# Generated by Django 3.1.7 on 2021-08-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_social_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_profile_pic_updated',
            field=models.BooleanField(default=False),
        ),
    ]
