# Generated by Django 3.1.7 on 2021-03-19 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='event.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('name', models.CharField(help_text='Venue Name', max_length=100)),
                ('global_id', models.CharField(help_text='Global Venue Id', max_length=30)),
                ('city', models.CharField(help_text='Venue Name', max_length=50)),
                ('address', models.CharField(help_text='Venue Address', max_length=100)),
                ('state_code', models.CharField(help_text='State Code', max_length=20)),
                ('state_name', models.CharField(help_text='State Name', max_length=50)),
                ('postal_code', models.CharField(help_text='Postal Code', max_length=10)),
                ('country_code', models.CharField(help_text='Country Code', max_length=20)),
                ('country_name', models.CharField(help_text='Country Name', max_length=50)),
                ('latitude', models.CharField(blank=True, help_text='Latitude', max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, help_text='Longitude', max_length=20, null=True)),
                ('url', models.URLField(blank=True, help_text='Venue Url', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_venue_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_venue_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10)),
                ('name', models.CharField(help_text='Event Name', max_length=100)),
                ('global_id', models.CharField(help_text='Global Event Id', max_length=30)),
                ('url', models.URLField(blank=True, help_text='Event Url', null=True)),
                ('price_min', models.CharField(blank=True, help_text='Price Range Min', max_length=10, null=True)),
                ('price_max', models.CharField(blank=True, help_text='Price Range Max', max_length=10, null=True)),
                ('event_status', models.CharField(help_text='Event Status', max_length=30)),
                ('currency', models.CharField(help_text='Currency', max_length=10)),
                ('image_json', models.JSONField()),
                ('seatmap_url', models.CharField(blank=True, help_text='Seat Map Url', max_length=255, null=True)),
                ('timezone', models.CharField(help_text='Timezone', max_length=30)),
                ('time', models.TimeField(blank=True, help_text='Event Timing', null=True)),
                ('date', models.DateField(blank=True, help_text='Event Date', null=True)),
                ('description', models.TextField(blank=True, help_text='Event Description', null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Event Category', null=True, on_delete=django.db.models.deletion.CASCADE, to='event.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_event_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_event_updated', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.venue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
