# Generated by Django 3.1.7 on 2021-03-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='global_id',
            field=models.CharField(help_text='Global Event Id', max_length=50),
        ),
        migrations.AlterField(
            model_name='venue',
            name='global_id',
            field=models.CharField(help_text='Global Venue Id', max_length=50),
        ),
    ]
