# Generated by Django 3.1.7 on 2021-02-23 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='time',
            field=models.TimeField(help_text='Event Timing'),
        ),
    ]
