# Generated by Django 3.1.7 on 2021-02-23 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210223_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20),
            preserve_default=False,
        ),
    ]
