# Generated by Django 3.1.7 on 2021-02-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventparticipant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], max_length=20),
        ),
    ]
