# Generated by Django 3.1.7 on 2021-02-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20210223_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='status',
        ),
    ]
