# Generated by Django 3.1.7 on 2021-02-24 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0005_remove_eventparticipant_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='created_on',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='updated_on',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='eventparticipant',
            old_name='created_on',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='eventparticipant',
            old_name='updated_on',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='eventparticipant',
            old_name='user',
            new_name='participant',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='event_status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')],max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_eventparticipant_created', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_eventparticipant_updated', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_eventtype_created', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtype',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtype',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_eventtype_updated', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_eventmodel_created', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Status', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_eventmodel_updated', to='auth.user'),
            preserve_default=False,
        ),
    ]
