# Generated by Django 3.1.7 on 2021-05-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_eventgroup_eventsetting_group_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, help_text='Custom Event Image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
