# Generated by Django 3.1.7 on 2021-05-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20210507_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Event Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(help_text='Venue Address', max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(help_text='Venue Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='country_name',
            field=models.CharField(help_text='Country Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(help_text='Venue Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='state_name',
            field=models.CharField(help_text='State Name', max_length=100),
        ),
    ]
