# Generated by Django 3.1.7 on 2021-05-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20210513_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='validity',
            field=models.IntegerField(choices=[(1, 'Monthly'), (6, 'HalfYearly'), (12, 'Yearly')], help_text='Validity in months'),
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
