# Generated by Django 3.1.7 on 2021-06-17 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_auto_20210616_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsetting',
            name='recurring_event',
            field=models.ForeignKey(help_text='Recurring Date and Time', null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.recurringevent'),
        ),
    ]
