# Generated by Django 3.1.7 on 2021-06-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_auto_20210622_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.ImageField(blank=True, help_text='Group Image', null=True, upload_to=''),
        ),
    ]
