# Generated by Django 3.1.7 on 2021-06-23 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_group_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsetting',
            name='recurring_event',
            field=models.ForeignKey(blank=True, help_text='Recurring Date and Time', null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.recurringevent'),
        ),
    ]
