# Generated by Django 3.1.7 on 2021-08-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_auto_20210729_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
