# Generated by Django 3.1.7 on 2021-08-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_notification_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='accepted',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
