# Generated by Django 3.1.7 on 2021-08-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_auto_20210824_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='Group Name', max_length=255),
        ),
    ]
